### ISSUE TITLE
Fine-Grained Activities of People Worldwide Figure 5 Result Reproduction

### ISSUE THREAD

**Issue by sy9267** [visym/heyvi#1]
Hello, I am currently trying to reproduce the results of Figure 5 in "Fine-Grained Activities of People Worldwide." 

The paper mentions that the baseline system used in the experiments is available at github.com/visym/heyvi, but I am confused because there are no clear explanations on the GitHub site or in the paper. 

Could you please tell me how to reproduce the values of Figure 5 in "Fine-Grained Activities of People Worldwide?" Please help me

**Comment by joefioresi718** [comment]
Adding to this thread to ask for the same thing, it would be helpful to have the baseline experiment code to get started working with the CAP dataset.

**Comment by jebyrne** [comment]
Here is the code to run the training and testing benchmarking for figures 5, 6, 7 and 8:

https://github.com/visym/cap/tree/main/benchmark

You will need to update your paths here:

https://github.com/visym/cap/blob/main/benchmark/cap_benchmark.py#L29-L136

This has not been tested on any other hardware configurations than our GPU cluster, so let me know if you run into any issues.

Reach out if you'd like the pretrained model for comparison.
